# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18q6L8hjK_3Ov0ZZFB4R9oXYti3S4OGaE
"""

def mean(data):
    return sum(data) / len(data)

def median(data):
    sorted_data = sorted(data)
    n = len(data)
    mid = n // 2
    return (sorted_data[mid] + sorted_data[-mid-1]) / 2 if n % 2 == 0 else sorted_data[mid]

def mode(data):
    frequency = {}
    for item in data:
        frequency[item] = frequency.get(item, 0) + 1
    max_frequency = max(frequency.values())
    return [item for item, freq in frequency.items() if freq == max_frequency]

def main():
    inputan = input('Masukkan deret bilangan untuk dataset (pisahkan dengan koma): ')
    data = list(map(int, inputan.split(',')))
    sorted_data = sorted(data)

    print("List Dataset:", sorted_data)
    print("Mean:", mean(sorted_data))
    print("Median:", median(sorted_data))
    print("Mode:", mode(sorted_data))

if __name__ == "__main__":
    main()