# -*- coding: utf-8 -*-
"""Menghitung Varians dan Stanar Deviasi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BnPgEFv1m0mc4NmYGEMdBiNlZ5kG3Phj

# Tugas Kelompok Praktikum PBF Modul 3

## Praktikum PBF RC | Kelompok 3
1.   Elok Fiola_122450051
2.   Vira Putri Maharani_122450129
3.   Rani Puspita Sari_122450030
4.   ⁠Diana syafithri 122450141
5.   Hermawan Manurung 122450069
6.   ⁠Jihan Putri Yani_121450161

### Program Menghitung Varians dan Standar Deviasi
Implementasikan fungsi untuk menghitung
varians dan standar deviasi dari sebuah dataset.
"""

import pandas as pd

def mean(data):
    return sum(data) / len(data)

def variance(data):
    mu = mean(data)
    return sum((x - mu) ** 2 for x in data) / (len(data) - 1)

def standard_deviation(data):
    return variance(data) ** 0.5

def clean_data(df):
    # Lakukan pembersihan data di sini sesuai kebutuhan
    df.dropna(inplace=True)  # Menghapus baris dengan nilai kosong
    return df

def read_csv_data(filename):
    try:
        df = pd.read_csv(filename)
        return df, None, filename
    except FileNotFoundError:
        return None, "File tidak ditemukan. Pastikan Anda memasukkan nama file yang benar.", None

# Penggunaan:
print("Silakan unggah file Anda dalam bentuk file.csv")
filename = input("Masukkan nama file CSV Anda: ")

df, error_message, file_name = read_csv_data(filename)
if error_message:
    print(error_message)
else:
    print("File CSV '{}' berhasil dibaca.".format(file_name))
    column_name = input("Masukkan nama label kolom yang ingin dianalisis: ")
    if column_name in df.columns:
        # Membersihkan data sebelum melakukan perhitungan
        df_cleaned = clean_data(df)

        if len(df) != len(df_cleaned):
            print("Data Anda telah dibersihkan.")
        else:
            print("Data Anda lengkap.")

        data = df_cleaned[column_name].tolist()
        banyak_data = len(data)
        print("\nDataset untuk kolom '{}':".format(column_name), data)

        result_table = [["Nama File", file_name],
                        ["Banyak Data", banyak_data],
                        ["Varians", variance(data)],
                        ["Standar Deviasi", standard_deviation(data)]]
        print("\nHasil Perhitungan")
        for row in result_table:
            print(row[0], ":", row[1])
    else:
        print("Label kolom '{}' tidak ditemukan dalam dataset.".format(column_name))

"""Pada percoban program ini kami menggunakan data primer. Data Rata-rata Jam Tidur Harian SD2022 merupakan dataset yang berisi 3 kolom dam 30 baris data. Dataset ini dikumpulkan menggunakan metode survei melalui Google Formulir. Subjek penelitiannya adalah Mahasiswa Sains Data Institut Teknologi Sumatera (ITERA) Angkatan 2022. Sampel yang didapatkan sebanyak 30 mahasiswa dimana mereka setuju jika data mereka dipublik. Data lengkap dapat diakses pada tautan berikut: https://github.com/elokfiola/Kelompok_3_RC_Praktikum_PBF/blob/0a3a28a676eb16a6bd39f137cb53b2ddb364e9a7/Rata-rata%20Jam%20Tidur%20Harian%20SD2022.csv"""